library(XML)
doc = readLines("http://2012.usopen.org/en_US/players/index.html")
pagetree = htmlTreeParse(doc, error = function(...){}, useInternalNodes = TRUE)
x = getNodeSet(pagetree,"//div[@class='men']/a")  
y = xmlSApply(x,function(x)xmlGetAttr(x,"href"))
y1 = paste("http://2012.usopen.org/en_US/players/",y)
y2 = gsub(" ","",y1)
doc.new = sapply(y2,function(x)readLines(x))
page.tree.new = sapply(doc.new,function(x)htmlTreeParse(x, error = function(...){}, useInternalNodes = TRUE))
length(page.tree.new)
x.new = sapply(page.tree.new,function(x)getNodeSet(x,"//div[@class='value']"))
xmlValue(x.new[[1]][[length(x.new[[1]])-1]])
hand = sapply(x.new,function(x)xmlValue(x[[length(x)-1]]))
namelist = sapply(page.tree.new,function(x)getNodeSet(x,"//div[@class='value upper']"))
name = sapply(namelist,xmlValue)
name.abbre = sapply(name,function(x)substring(x,1,4))
handedness = as.data.frame(cbind(name,hand))
WriteXLS("handedness","handedness.xls")
